---
title: "Part I - Explore"
author: "Jesse O."
date: "18/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Chapter 1 - Data Visualisation with ggplot2
```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes (x = displ, y = hwy))
```

```{r}
ggplot(data = mpg)

```

```{r}
mtcars
```

```{r}
nrow(mtcars)
```

```{r}
ncol(mtcars)
```

```{r}
?mpg
```

```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = cyl, y = hwy))
```

```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = drv, y = class))
```

```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(
    x = displ,
    y = hwy,
    colour = class
  ))
```

```{r}
ggplot(data = mpg) +
  geom_point(
    mapping = aes(
      x = displ,
      y = hwy,
      size = class,
      colour = class
    )
  )
```

```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(
    x = displ,
    y = hwy,
    alpha = class
    )
  )
```

```{r}
ggplot(data = mpg)+
  geom_point(
    mapping = aes(
      x = displ,
      y = hwy,
      shape = class
    )
  )
```

```{r}
# To set an aesthetic manually, it has to be done oustside the aes()

ggplot(data = mpg) +
  geom_point(
    mapping = aes(
      x = displ,
      y = hwy
    ),
    colour = "blue"
  )
```



